---

## some packages need multiverse like snmp-mibs-downloader
- apt_repository: repo="{{item}}"
  register: multiverse_installed
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'

- apt: update_cache=yes
  when: multiverse_installed | changed

## check no issue but not idempotent...
#- command: 'dpkg --configure -a'

- name: Install MHN Client - amun
  include: deploy_amun.yml
  when: amun is defined and amun

- name: Install MHN Client - Dionaea
  include: deploy_dionaea.yml
  when: dionaea is defined and dionaea

- name: Install MHN Client - elastichoney
  include: deploy_elastichoney.yml
  when: elastichoney is defined and elastichoney

- name: Install MHN Client - glastopf
  include: deploy_glastopf.yml
  when: glastopf is defined and glastopf

- name: Install MHN Client - kippo
  include: deploy_kippo.yml
  when: kippo is defined and kippo

- name: Install MHN Client - p0f
  include: deploy_p0f.yml
  when: p0f is defined and p0f

- name: Install MHN Client - shockpot
  include: deploy_shockpot.yml
  when: shockpot is defined and shockpot

- name: Install MHN Client - wordpot
  include: deploy_wordpot.yml
  when: wordpot is defined and wordpot

- name: Install MHN Client - snort
  include: deploy_snort.yml
  when: snort is defined and snort

