---

- name: deploy mhn logstash configuration on logstash server
  template: src=logstash-mhn.conf.j2 dest=/etc/logstash/conf.d/90-mhn.conf mode=0644 backup=yes
#  delegate_to: "{{ mhn_elk_logstashserver }}"
  notify:
    - restart logstash

- name: deploy mhn elasticsearch template on elastic server
  template: "src=logstash-mhn.conf.j2 dest={{ mhn_elk_elasticserver_templatesdir }}/logstash-mhn.conf mode=0644 backup=yes"
  delegate_to: "{{ mhn_elk_elasticserver }}"
#  notify:
#    - restart elasticsearch

