---

- name: apt | Install hpfeeds dependencies
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - libffi-dev
    - build-essential
    - python-pip
    - python-dev
    - git
    - libssl-dev
    - python-virtualenv
    - libev-dev
    - supervisor
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | Install hpfeeds dependencies
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - "@Development tools"
    - libffi-devel
    - python-devel
    - python-virtualenv
    - git
    - openssl-devel
    - libev-devel
    - supervisor
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install mongodb
  include: mongodb.yml

- stat: path=/opt/hpfeeds
  register: githpfeeds
- name: git clone hpfeeds
  git:
    repo=https://github.com/threatstream/hpfeeds
    dest=/opt/hpfeeds
  when: not githpfeeds.stat.exists

## FIXME! v2.2: https://github.com/ansible/ansible-modules-core/issues/5470
- name: Install hpfeeds virtualenv - initiate virtualenv because of bug, install modules after
  pip: name=cffi state=present virtualenv=/opt/hpfeeds/env
- name: Install hpfeeds virtualenv
  pip:
    name: "{{item}}"
    state: present
#    virtualenv: /opt/hpfeeds/env
    executable: /opt/hpfeeds/env/bin/pip
  with_items:
    - cffi
## FIXME! AssertionError: sorry, but this version only supports 100 named groups + Current: 16.2.0 ~ 0.16.2/same error
## https://github.com/pyca/cryptography/issues/3187
#    - pycparser==2.14
    - pyopenssl==0.14
    - pymongo
## FIXME! never detected as installed = changed at each run
    - git+https://github.com/rep/evnet.git#egg=evnet-dev
    - file:///opt/hpfeeds

- name: ensure appropriate permissions for /var/log/mhn
  file: path=/var/log/mhn state=directory mode=755

- name: set hpfeeds supervisor config
  copy: "src=hpfeeds-broker.conf dest={{ supervisor_confdir }}/hpfeeds-broker.{{ supervisor_ext }} mode=0644"
  notify:
    - supervisor update

