---
- name: Ubuntu | Install hpfeeds dependencies
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - libffi-dev
    - build-essential
    - python-pip
    - python-dev
    - git
    - libssl-dev
    - python-virtualenv
    - libev-dev
    - supervisor
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Debian | install mongodb
  include: mongodb.yml

- stat: path=/opt/hpfeeds
  register: githpfeeds
- name: git clone hpfeeds
  git:
    repo=https://github.com/threatstream/hpfeeds
    dest=/opt/hpfeeds
  when: not githpfeeds.stat.exists

- name: Install hpfeeds virtualenv
  pip: name="{{item}}" state=present
    virtualenv=/opt/hpfeeds/env
  with_items:
    - cffi
    - pyopenssl==0.14
    - pymongo
## FIXME! never detected as installed = changed at each run
    - git+https://github.com/rep/evnet.git#egg=evnet-dev
    - file:///opt/hpfeeds

- file: path=/var/log/mhn state=directory mode=755

- copy: src=hpfeeds-broker.conf dest=/etc/supervisor/conf.d/hpfeeds-broker.conf mode=0644
  notify:
    - supervisor update

