---
- block:
    - name: Ubuntu | Add Mongodb repository key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10
    - name: Ubuntu | Add Mongodb repository
      apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
  when: (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int < 16)
## https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
- block:
    - name: Apt | Add Mongodb repository key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927
    - name: Debian | Add Mongodb repository
      apt_repository: repo='deb http://repo.mongodb.org/apt/{{ ansible_distribution|lower }} {{ ansible_distribution_release }}/mongodb-org/3.2 main' state=present
      when: ansible_distribution == 'Debian'
    - name: Ubuntu | Add Mongodb repository
      apt_repository: repo='deb http://repo.mongodb.org/apt/{{ ansible_distribution|lower }} {{ ansible_distribution_release }}/mongodb-org/3.2 multiverse' state=present
      when: ansible_distribution == 'Ubuntu'
    - name: configure systemd config file (not included)
## FIXME! FAILED! => {"changed": true, "failed": true, "msg": "Destination /lib/systemd/system not writable"}
#      template: src=mongodb.service.j2 dest=/lib/systemd/system/mongod.service mode=0644
      template: src=mongodb.service.j2 dest=/usr/lib/systemd/system/mongod.service mode=0644
## http://askubuntu.com/questions/757384/can-i-use-14-04-mongodb-packages-with-16-04
    - name: enable service mongodb
      service: name={{ mongodb_svc }} enabled=yes state=started
#    - name: unmask mongodb from systemctl
#      command: "systemctl unmask mongodb"
  when: ansible_distribution == 'Debian' or (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16)

## https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/
- block:
    - name: install mongodb rpm key
      rpm_key: key=https://www.mongodb.org/static/pgp/server-3.2.asc state=present
    - name: install mongodb yum repository
      template: src=mongodb.repo.j2 dest=/etc/yum.repos.d/mongodb.repo mode=0644
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: apt | Install mongodb
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - mongodb-org
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | Install mongodb
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - mongodb-org
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

## disappeared in mongodb3, https://docs.mongodb.com/manual/tutorial/rotate-log-files/
#- name: set log rotation for mongodb
#  lineinfile: dest=/etc/mongod.conf line="{{ item }}"
#  with_items:
#    - 'logpath=/var/log/mongodb/mongod.log'
#    - 'logrotatesize=20M'
#    - 'logrotatebackups=7'

- name: evaluating /var/lib/mongodb
  stat: path=/var/lib/mongodb
  register: mongodblib
- block:
    - name: ensure appropriate permissions for /var/lib/mongodb
      file: dest={{ item }} owner=mongodb
      with_fileglob:
        - /var/lib/mongodb/*
## {"failed": true, "item": "/var/lib/mongodb/local.ns", "msg": "file (/var/lib/mongodb/local.ns) is absent, cannot continue", "path": "/var/lib/mongodb/local.ns", "state": "absent"}
      ignore_errors: true
  when: mongodblib.stat.exists

